---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ansible_omnibus: false
  require_ansible_repo: false
  requirements_path: requirements.yml
  ansible_version: 2.4.3.0
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ignore_paths_from_root:
    - .kitchen
  ssh_known_hosts:
    - github.com

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: solita/ubuntu-systemd
      platform: ubuntu
      privileged: true
      run_command: /sbin/init
      provision_command:
        - apt-get update
        - apt-get install -y iproute git python-pip curl
        - pip install ansible==2.4.3.0 pyhamcrest pyOpenSSL>=0.14
  - name: centos-7.2
    driver_config:
      image: centos/systemd
      platform: centos
      privileged: true
      run_command: /sbin/init
      provision_command:
        - yum install -y iproute tuned epel-release ansible git cronie initscripts libselinux-python policycoreutils-python
        # https://github.com/CentOS/CentOS-Dockerfiles/issues/173
        - systemctl enable systemd-user-sessions.service && ln -s /usr/lib/systemd/system/systemd-user-sessions.service /etc/systemd/system/default.target.wants/systemd-user-sessions.service


suites:
  - name: master
    driver:
      forward:
       - 7007:8080
      network:
        - ["private_network", { ip: "172.29.129.172" }]

  - name: slave
    driver:
      network:
        - ["private_network", { ip: "172.29.129.191" }]

transport:
  forward_agent: true
